name: Check Unit Tests in Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check_unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v3
      with:
        files: "*Test.java"
    
    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      run: echo All files exist!
      
    - name: File does not exist
      if: steps.check_files.outputs.files_exists != 'true'
      run: echo "No Test files found. Please add Tests."
