name: Check Unit Tests in Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  check-tests:
    runs-on: ubuntu-latest
    env:
      CUSTOM_FLAG: RED FLAG for unit-test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: "11"
      - name: Check for test files
        run: |
          # Use find to recursively search for all files with names matching a
          test pattern

          test_files=$(find . -type f -name '*Test*' -o -name '*Spec*')


          # Check if any test files are found

          if [ -n "$test_files" ]; then
            echo "Test files exist!"
          else
            echo "Error: Pull request must include at least one test file."
            exit 1
          fi
